### ISSUE TITLE
Error on pages with tables

### ISSUE THREAD

**Issue by bl79** [earwig/mwparserfromhell#148]
On pages with tables parser don't find templates, and has writes in tables the bad char '|'.
E.g. page: https://ru.wikipedia.org/wiki/%D0%A8%D0%BF%D0%B8%D1%86%D0%B1%D0%B5%D1%80%D0%B3%D0%B5%D0%BD When parser run on text of this page with the code
```
import mwparserfromhell
f = open('page.txt', 'r', encoding='utf-8')
text = f.read()
f.close()
code = mwparserfromhell.parse(text)
for template in code.filter_templates():
	print(template)
```
then be print only a few recognized templates, e.g. be skip all bibliographic templates.

And this code add in tables '|' like: 
> {| style="float:right" class="standard"    →  **{||** style="float:right" class="standard" 
> {|class="wikitable" style="text-align:right"   →  **{||**class="wikitable" style="text-align:right" 

if save the file:
```
f = open('page.txt', 'w', encoding='utf-8')
f.write(str(code))
f.close()
```

**Comment by earwig** [comment]
This was fixed in 61b6b984702288a4771f45a4a139d28b74988c4f. Try using the `develop` branch.

**Comment by bl79** [comment]
Still dont works. '|' doesn't add, but still doesn't see templates.

**Comment by earwig** [comment]
Looks like #40 due to constructs like:

    |<center>14 443

No fix yet, unfortunately.
